# Generated by Django 3.2.9 on 2023-10-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_book_cover_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
