# Generated by Django 3.2.9 on 2023-10-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_alter_book_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='color',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
