# Generated by Django 3.2.9 on 2023-10-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_alter_book_cover_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Uzbek', 'Uzbek'), ('Russia', 'Russia'), ('English', 'English')], default='Uzbek', max_length=100),
        ),
    ]
