# Generated by Django 3.2.9 on 2023-10-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0037_remove_book_hardcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
