# Generated by Django 3.2.9 on 2023-10-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.TextField(choices=[('Uzbek', 'Uzbek'), ('Russia', 'Russia'), ('English', 'English')], default='Uzbek', max_length=100),
        ),
    ]
