# Generated by Django 3.2.9 on 2023-10-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0040_auto_20231027_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language_ru',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language_uz',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Uzbek', 'Uzbek'), ('Russia', 'Russia'), ('English', 'English')], default='Uzbek', max_length=100),
        ),
    ]
